name: Deploy to Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Code to Staging
        run: |
          # Switch to the staging branch
          git checkout staging

          # Copy all files from the dev branch to the staging branch
          git checkout main -- .

          # Commit the changes
          git add .
          git commit -m "Copy code from main to staging"

          # Push the changes to the staging branch
          git push origin staging
