name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Code to Dev
        run: |
          # Switch to the staging branch
          git checkout Dev

          # Copy all files from the dev branch to the Dev branch
          git checkout main -- .

          # Commit the changes
          git add .
          git commit -m "Copy code from main to Dev"

          # Push the changes to the staging branch
          git push origin Dev
